# train options
seed: 2020 # sacred handles automatic seeding when passed in the config
batch_size: 32
workers: 4
epochs: 50
dataset: "CIFAR10"
model: "ResNetGATCN"  # "ResNet" or "ResNetGCN" or "ResNetGATCN"

# loss options
lr: 1.0e-3
momentum: 0.9
weight_decay: 1.0e-6

# data folder
root: "../data"
# save model every checkpoint epochs
checkpoint: 2
# proportion of validation data
valsize: 0.2

# parameters for testing model
experiment_id: 1
checkpoin_to_test: 10

