# train options
seed: 1234567 # sacred handles automatic seeding when passed in the config
batch_size: 128
workers: 4
epochs: 50
dataset: "CIFAR10"
model: "ContrastiveResNet"
pretrained_encoder: "../pretrained_models/resnet18_supervised.pth"  # or null  or "../pretrained_models/resnet18_supervised.pth"
temperature: 0.5
projection_dim: 128
num_neg: 10

# loss options
lr: 0.1
momentum: 0.9
weight_decay: 5.0e-4

# data folder
root: "../data"
# proportion of validation data
valsize: 0.1

# evaluation arguments
test_model: "../pretrained_models/contrastive_nneg10.pth"
n_neighbors: 3
