# train options
seed: 2020 # sacred handles automatic seeding when passed in the config
batch_size: 128
workers: 0
epochs: 50
dataset: "CIFAR10"
model: "ContrastiveResNetGCN"  # "ResNet" or "ResNetGCN" or "ResNetGATCN" or "ContrastiveResNetGCN"
graph_type: "FC"  # "FC" or "K-MEAN" or "Empty" ("Empty" is for testing)
temperature: 0.5
projection_dim: 128

# loss options
lr: 0.001
momentum: 0.9
weight_decay: 5.0e-4

# data folder
root: "../data"
# save model every checkpoint epochs
checkpoint: 30
# proportion of validation data
valsize: 0.1

# parameters for testing model
experiment_id: 1
checkpoin_to_test: 10

